name: 'airflow_warehouse'
version: '1.0'
config-version: 2

profile: 'airflow_warehouse'

model-paths: ["../models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airflow_warehouse:
    cleansed:
      +schema: cleansed
      +materialized: table
    raw:
      +schema: raw
      +materialized: view
